export const data = [
  {
    available: '1',
    brand: 'BAUER',
    model: 'BS-6MHB5-EL 330',
    power: '330',
    width: '1002',
    height: '1694',
    warranty: '20',
    powerWarranty: '25',
    price: '420',
    description:
      'Panele fotowoltaiczne niemieckiej marki Bauer to wysokiej jako?ci modu?y w ca?o?ci wykonane w kolorze czarnym. Wyko?czenie Full Black podnosi walory estetyczne instalacji poprzez g??boki, ciemny kolor i brak widocznych kropek pomi?dzy poszczeg�lnymi ogniwami. Wysoka wydajno?? ciemnoczarnych monokrystalicznych p�?ogniw krzemowych dzi?ki zastosowaniu technologii PERC (Passivated Emitter and Rear Cell) oraz 5 elektrodom na powierzchni ka?dego ogniwa',
    datasheet: '',
    ncrfg: '',
  },
  {
    available: '1',
    brand: 'JA Solar',
    model: 'JAM60S10 340/MR',
    power: '340',
    width: '996',
    height: '1689',
    warranty: '12',
    powerWarranty: '25',
    price: '367',
    description:
      'Monokrystaliczny panel fotowoltaiczny firmy JA Solar charakteryzuje si? wysok? sprawno?ci? oraz ?ywotno?ci? wykonany w technologii ogniw po?�wkowych. Wykonanie w technologii ogniw po?�wkowych cechuje ni?sza rezystancja wewn?trzna orazstraty mocy o 1/4 w stosunku do Panel�w opartych na konstrukcji klasycznej (o pe?nych ogniwach). Dodatkowo Panele wykonane w technologii ogniw po?�wkowych poza generowaniem wi?kszej mocy wyj?ciowej, dzia?aj? lepiej podczas codziennej pracy w wyniku ni?szegowsp�?czynnika temperaturowego mocy oraz zmniejszonego wp?ywu zacienienia na wytwarzanie energii.Wykonany w wersji z czarn? ram?',
    datasheet: '',
    ncrfg: '',
  },
  {
    available: '1',
    brand: 'JA Solar',
    model: 'JAM60S20-380/MR-BF',
    power: '380',
    width: '1052',
    height: '1776',
    warranty: '12',
    powerWarranty: '25',
    price: '420',
    description:
      'Panel fotowoltaiczny JA SOLAR 380W/MR-BF wykonany w technologii monokrystalicznej, cechuje si? podwy?szon? do 20,3% sprawno?ci?. Panel jest wykonany w technologii�ogniw multibusbarowych ci?tych na p�?, kt�ra polega na zastosowaniu w ogniwach a? 9 ?cie?ek przewodz?cych pr?d (bus bar) zamiast tradycyjnie od 3 do 5. Wi?ksza liczba przek?ada si? na wi?ksz? odporno?? na mikrop?kni?cia powoduj?ce zmniejszanie mocy panelu. Panele cechuj? si? tak?e zwi?kszonym dopuszczalnym obci??eniem pr?dem rewersyjnym (zacienienie!).',
    datasheet: '',
    ncrfg: '',
  },
  {
    available: '1',
    brand: 'LONGi Solar',
    model: 'LR4-60HPH 375M',
    power: '375',
    width: '1038',
    height: '1755',
    warranty: '10',
    powerWarranty: '25',
    price: '480',
    description:
      'LONGi Solar�jest wiod?cym producentem wysokiej sprawno?ci modu?�w fotowoltaicznych. Producent od ponad 18 lat skupia si? na technologii monokrystalicznej co uczyni?o go najwi?kszym producentem monokrystalicznych wafli i modu?�w fotowoltaicznych. Najwi?kszy dostawca w Chinach oraz TOP 3 na ?wiecie.',
    datasheet: '',
    ncrfg: '',
  },
  {
    available: '0',
    brand: 'LONGi Solar',
    model: 'LR4-72HPH-445M',
    power: '445',
    width: '1038',
    height: '2094',
    warranty: '12',
    powerWarranty: '25',
    price: '560',
    description:
      'LONGi Solar jest wiod?cym producentem wysokiej sprawno?ci modu?�w fotowoltaicznych. Producent od ponad 18 lat skupia si? na technologii monokrystalicznej co uczyni?o go najwi?kszym dostawc? monokrystalicznych ogniw krzemowych.',
    datasheet: '',
    ncrfg: '',
  },
  {
    available: '1',
    brand: 'Q Cells',
    model: 'Q.PEAK DUO G6',
    power: '360',
    width: '1030',
    height: '1740',
    warranty: '12',
    powerWarranty: '25',
    price: '450',
    description:
      'Panel fotowoltaiczny�Q CELLS Q.PEAK DUO-G6 350�wykonany w�technologii monokrystalicznej, cechuje si? podwy?szon? do�19,5% sprawno?ci?. Zastosowano wykonanie w technologii�ogniw multibusbarowych ci?tych na p�?. Technologia�Q.ANTUM�polega na wykorzystaniu w?a?ciwo?ci specjalnego nano pokrycia dla pod?o?a ogniw. Dzi?ki wi?kszemu napromienieniu, ogniwa wykonane ze standardowych materia?�w uzyskuj? wydajno?? wy?sz? o nawet 18%. Panele fotowoltaiczne wykonane w takiej technologii uzyskuj? podwy?szon? wydajno?? w rzeczywisty',
    datasheet: '',
    ncrfg: '',
  },
];
